version: "3.9"

services:
  app:
    image: literallyme1/fan-cafe-app-test:latest
    container_name: fan-cafe-app-test
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    env_file:
      - .env.awstest
    environment:
      - SPRING_PROFILES_ACTIVE=awstest
    restart: unless-stopped
    depends_on:
      - rabbitmq
    logging:
      driver: "awslogs"
      options:
        awslogs-group: "fan-cafe-logs"
        awslogs-region: "ap-northeast-2"
        awslogs-stream: "app-server"
        awslogs-create-group: "true"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-test
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    restart: unless-stopped