spring.application.name=fan-cafe

# --- Database ---
spring.datasource.url=jdbc:mysql://localhost:3306/fan_cafe
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=false
spring.sql.init.mode=always
spring.sql.init.separator=;;

# --- Redis ---
spring.data.redis.host=localhost
spring.data.redis.port=6379

# --- AWS / S3 ---
spring.cloud.aws.region.static=ap-northeast-2
spring.cloud.aws.s3.bucket=fan-cafe

# --- Mail ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# --- Server ---
server.port=8080

# --- Actuator Basic Auth ---
spring.security.user.name=healthcheck
spring.security.user.password=strong-health-password
spring.security.user.roles=ACTUATOR

# --- Slack ---
slack.webhook.enabled=true

# --- MQ ---
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
