spring.application.name=fan-cafe
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# --- Database ---

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# --- Redis ---
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

# --- AWS / S3 ---
spring.cloud.aws.region.static=${AWS_REGION}
spring.cloud.aws.s3.bucket=${AWS_S3_BUCKET}

# --- Mail ---
spring.mail.host=smtp.gmail.com
spring.mail.port=${MAIL_PORT}

# --- Server ---
server.port=${SERVER_PORT}

# --- Actuator Basic Auth ---
spring.security.user.name=${ACTUATOR_USER}
spring.security.user.password=${ACTUATOR_PASSWORD}
spring.security.user.roles=ACTUATOR

# --- Slack ---
slack.webhook.enabled=true

# --- MQ ---
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}
