spring.datasource.url=jdbc:mysql://localhost:3306/fan_cafe
spring.datasource.username=root
spring.datasource.password=0000
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cloud.aws.region.static=ap-northeast-2
spring.cloud.aws.credentials.access-key=AKIASIVGLJH5DJODTFHF
spring.cloud.aws.credentials.secret-key=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
spring.cloud.aws.s3.bucket=fan-cafe-bucket
spring.cloud.aws.stack.auto=false


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=kkh80217891@gmail.com
spring.mail.password=twlxaiputrcylrtj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

management.endpoint.health.show-details=always

slack.webhook.enabled=true
slack.webhook.url=https://hooks.slack.com/services/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