
spring.application.name=fan-cafe
logging.level.root=WARN
# --- Database  ---
spring.datasource.url=${DB_URL:?DB_URL is required}
spring.datasource.username=${DB_USERNAME:?DB_USERNAME is required}
spring.datasource.password=${DB_PASSWORD:?DB_PASSWORD is required}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.hikari.maximum-pool-size=50
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=false

# --- Redis  ---
spring.data.redis.host=${REDIS_HOST:?REDIS_HOST is required}
spring.data.redis.port=${REDIS_PORT:?REDIS_PORT is required}
spring.data.redis.lettuce.pool.max-active=50
spring.data.redis.lettuce.pool.max-idle=10
spring.data.redis.lettuce.pool.min-idle=5
spring.data.redis.lettuce.pool.max-wait=5000ms

# --- AWS / S3  ---
spring.cloud.aws.region.static=ap-northeast-2
spring.cloud.aws.s3.bucket=fan-cafe

# --- Mail ---
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# --- Server ---
server.port=${SERVER_PORT:?SERVER_PORT is required}

# --- Actuator Basic Auth ---
spring.security.user.name=${ACTUATOR_USER:?ACTUATOR_USER is required}
spring.security.user.password=${ACTUATOR_PASSWORD:?ACTUATOR_PASSWORD is required}
spring.security.user.roles=ACTUATOR
management.endpoints.web.exposure.include=*

# --- Slack ---
slack.webhook.enabled=true
slack.webhook.url=${SLACK_WEBHOOK_URL}

# --- MQ ---
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

# --- Metrics (HTTP P95) ---
management.metrics.distribution.percentiles.http.server.requests=0.95
management.metrics.distribution.percentiles-histogram.http.server.requests=true

spring.sql.init.mode=always
spring.sql.init.separator=;;
spring.sql.init.data-locations=classpath:data-outbox.sql
redis.warmup.enabled = false
spring.data.redis.ssl.enabled=true