spring.application.name=fan-cafe
spring.profiles.active=local
jwt.private-key-path=classpath:key/private_key.pem
jwt.public-key-path=classpath:key/public_key.pem
firebase.service-account-path=classpath:firebase/service-account.json
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=1209600000
spring.http.encoding.charset=UTF-8
logging.level.root=INFO
spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=when_authorized

