spring.application.name=fan-cafe

spring.profiles.active=local

#Jwt Toke (access : 15, refresh : 14)
jwt.private-key-path = classpath:keys/private.pem
jwt.public-key-path = classpath:keys/public.pem
jwt.access-token-expiration=900000
jwt.refresh-token-expiration = 1209600000



