spring.application.name=fan-cafe

#Redis
spring.redis.host= localhost
spring.redis.port=6379

spring.security.user.name=healthcheck
spring.security.user.password=strong-health-password
spring.security.user.roles=ACTUATOR

management.endpoint.health.show-details=when_authorized