spring.datasource.url=${PAYMENT_DB_URL:jdbc:mysql://localhost:3308/payment_db?allowPublicKeyRetrieval=true&useSSL=false}
spring.datasource.username=${PAYMENT_DB_USERNAME:root}
spring.datasource.password=${PAYMENT_DB_PASSWORD:root}
spring.datasource.hikari.maximum-pool-size=20

experiment.payment.partial-success-enabled=${EXPERIMENT_PAYMENT_PARTIAL_SUCCESS_ENABLED:false}
experiment.payment.partial-success-percent=${EXPERIMENT_PAYMENT_PARTIAL_SUCCESS_PERCENT:20}
experiment.payment.approval-response-delay=${EXPERIMENT_PAYMENT_APPROVAL_RESPONSE_DELAY:5s}

spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USERNAME:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
