spring.application.name=payment-service
server.port=${PAYMENT_SERVER_PORT:8081}

spring.datasource.url=${PAYMENT_DB_URL:jdbc:mysql://localhost:3308/payment_db?allowPublicKeyRetrieval=true&useSSL=false}
spring.datasource.username=${PAYMENT_DB_USERNAME:root}
spring.datasource.password=${PAYMENT_DB_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

mock.pg.webhook-secret=${MOCK_PG_WEBHOOK_SECRET:local-mock-pg-webhook-secret}
management.endpoints.web.exposure.include=health
